
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author om
 */
public class AvpsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AvpsAdmin
     */
    public AvpsAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Searchemp = new javax.swing.JPanel();
        panal1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        mcb = new javax.swing.JComboBox<>();
        m = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vt = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ViewSlots = new javax.swing.JPanel();
        Searchemp1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        panal2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vt1 = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        v4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        slotUpdate = new javax.swing.JButton();
        v6 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        NewEmp = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        t4 = new javax.swing.JPasswordField();
        VehicleEntry_ = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cm = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        availStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehicleNo = new javax.swing.JTextField();
        pButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        s11 = new javax.swing.JLabel();
        s55 = new javax.swing.JLabel();
        s33 = new javax.swing.JLabel();
        s22 = new javax.swing.JLabel();
        s44 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        slipcancel = new javax.swing.JButton();
        slipPrint = new javax.swing.JButton();
        Vehiclexit = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        cbx = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        ex1 = new javax.swing.JLabel();
        ex5 = new javax.swing.JLabel();
        ex2 = new javax.swing.JLabel();
        ex3 = new javax.swing.JLabel();
        ex4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        ex6 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        ex7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 51, 255));
        jLabel26.setText("Employee ID :");
        panal1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        mcb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));
        mcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcbActionPerformed(evt);
            }
        });
        panal1.add(mcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 43, 96, -1));

        m.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mKeyReleased(evt);
            }
        });
        panal1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 261, 37));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("GO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panal1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("Get All Emp");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panal1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));

        vt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee Name", "Phone"
            }
        ));
        vt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vt);

        panal1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 297));

        jButton12.setBackground(new java.awt.Color(102, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setText("New Employee");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panal1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 227, 68));

        edit.setBackground(new java.awt.Color(102, 255, 255));
        edit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        edit.setText("Edit Employee");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        panal1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 227, 68));

        delete.setBackground(new java.awt.Color(102, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setText("Delete Employee");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        panal1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, -1, 68));

        jLabel27.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 51, 255));
        jLabel27.setText("Search Employee By");
        panal1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 43, -1, 35));

        jLabel28.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 51, 255));
        jLabel28.setText("Employee Name :");
        panal1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jLabel29.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 255));
        jLabel29.setText("Phone :");
        panal1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, 30));
        panal1.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 496, 205, 30));

        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        panal1.add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 205, -1));
        panal1.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 218, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/blue car.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        panal1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        Searchemp.add(panal1);

        getContentPane().add(Searchemp, "card6");

        ViewSlots.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ViewSlots.add(Searchemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 153, 255));

        jLabel31.setFont(new java.awt.Font("Aharoni", 1, 36)); // NOI18N
        jLabel31.setText("Total and Vacant Slots");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(299, 299, 299))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel31)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ViewSlots.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 90));

        panal2.setBackground(new java.awt.Color(204, 255, 255));
        panal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 255));
        jLabel30.setText("Floor No :");
        panal2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        vt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Floor No", "Vehicle Type", "Total Slots", "Vacant Slots"
            }
        ));
        vt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vt1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vt1);

        panal2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 750, 250));

        refresh.setBackground(new java.awt.Color(255, 51, 255));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        panal2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 227, 100));

        edit1.setBackground(new java.awt.Color(255, 51, 255));
        edit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        edit1.setText("Edit ");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        panal2.add(edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 227, 100));

        jLabel33.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 51, 255));
        jLabel33.setText("Vacant Slots :");
        panal2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jLabel34.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 255));
        jLabel34.setText("Total Slots :");
        panal2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 30));

        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });
        panal2.add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 205, 30));

        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });
        panal2.add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 205, -1));
        panal2.add(v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 218, 30));

        jLabel35.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 51, 255));
        jLabel35.setText("Vehicle Type :");
        panal2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, 30));

        slotUpdate.setBackground(new java.awt.Color(255, 102, 255));
        slotUpdate.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        slotUpdate.setText("Update");
        slotUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotUpdateActionPerformed(evt);
            }
        });
        panal2.add(slotUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));
        panal2.add(v6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 218, 30));

        ViewSlots.add(panal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1020, 510));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/blue car.jpg"))); // NOI18N
        jLabel32.setText("jLabel32");
        ViewSlots.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1040, 640));

        getContentPane().add(ViewSlots, "card4");

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));

        jLabel18.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("New  Employee");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(31, 31, 31))
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/1406942498751_wps_6_Hands_on_a_steering_wheel.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(51, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 612));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Employee details");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 310, -1));

        jPanel6.setBackground(new java.awt.Color(255, 204, 255));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel21.setText("Employee ID :");

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel22.setText("Employee Name :");

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel23.setText("Phone :");

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel24.setText("Password :");

        jButton5.setBackground(new java.awt.Color(153, 0, 153));
        jButton5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REGISTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 0, 153));
        jButton6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CLEAR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(63, 63, 63)
                        .addComponent(jButton6)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t1)
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(t4))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22)))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewEmpLayout = new javax.swing.GroupLayout(NewEmp);
        NewEmp.setLayout(NewEmpLayout);
        NewEmpLayout.setHorizontalGroup(
            NewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewEmpLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(NewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewEmpLayout.setVerticalGroup(
            NewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewEmpLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(NewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewEmpLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)))
        );

        getContentPane().add(NewEmp, "2");

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehicle Entry");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setText("Avps parking slip");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));

        jLabel3.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("Vehicle Type:");

        cm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAR", "BIKE" }));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("Check Availability");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        availStatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        availStatus.setForeground(new java.awt.Color(255, 204, 255));
        availStatus.setText("...");

        jLabel5.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("Vehicle No :");

        vehicleNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        pButton.setBackground(new java.awt.Color(255, 204, 255));
        pButton.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        pButton.setText("SUBMIT");
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(vehicleNo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(availStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(availStatus)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Vehicle Type : ");

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("SlipNo : ");

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Vehicle No :");

        jLabel9.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("IN Date & Time :");

        jLabel10.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Floor No :");

        s11.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        s55.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        s33.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        s22.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        s44.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 153));
        jLabel16.setText("Parking Charges: Bike- Rs. 20/- , Car- Rs. 30/- per hour");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("Please do not leave any valuables inside the vehicle.");

        slipcancel.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        slipcancel.setText("Cancel");
        slipcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slipcancelActionPerformed(evt);
            }
        });

        slipPrint.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        slipPrint.setText("Print");
        slipPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slipPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VehicleEntry_Layout = new javax.swing.GroupLayout(VehicleEntry_);
        VehicleEntry_.setLayout(VehicleEntry_Layout);
        VehicleEntry_Layout.setHorizontalGroup(
            VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleEntry_Layout.createSequentialGroup()
                .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VehicleEntry_Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VehicleEntry_Layout.createSequentialGroup()
                                .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addGroup(VehicleEntry_Layout.createSequentialGroup()
                                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addGap(31, 31, 31)
                                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s44, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s33, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s55, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 109, Short.MAX_VALUE))
                            .addGroup(VehicleEntry_Layout.createSequentialGroup()
                                .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VehicleEntry_Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(104, 104, 104)
                                        .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleEntry_Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slipPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(slipcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        VehicleEntry_Layout.setVerticalGroup(
            VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleEntry_Layout.createSequentialGroup()
                .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VehicleEntry_Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VehicleEntry_Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(VehicleEntry_Layout.createSequentialGroup()
                                .addComponent(s44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s55, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addGroup(VehicleEntry_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(slipcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slipPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );

        getContentPane().add(VehicleEntry_, "card7");

        jPanel7.setBackground(new java.awt.Color(102, 0, 102));

        jLabel37.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Vehicle Exit");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 255));

        jLabel38.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel38.setText("Avps parking bill");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel38)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(113, 113, 113))
        );

        jPanel9.setBackground(new java.awt.Color(51, 0, 51));

        jLabel39.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 204, 255));
        jLabel39.setText("Search By:");

        cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SLIP NO", "VEHICLE NO" }));
        cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 204, 255));
        jLabel40.setText("Slip No :");

        s1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(40, 40, 40)
                        .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(27, 27, 27)
                        .addComponent(s1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel41.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 0, 51));
        jLabel41.setText("Vehicle Type : ");

        jLabel42.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 0, 51));
        jLabel42.setText("SlipNo : ");

        jLabel43.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 0, 51));
        jLabel43.setText("Vehicle No :");

        jLabel44.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 0, 51));
        jLabel44.setText("IN Date & Time :");

        jLabel45.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 0, 51));
        jLabel45.setText("Revenue:");

        ex1.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex5.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex2.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex3.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex4.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        jButton10.setBackground(new java.awt.Color(51, 0, 51));
        jButton10.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 204, 255));
        jButton10.setText("Print Bill");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(51, 0, 51));
        jButton11.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 204, 255));
        jButton11.setText("Collect Revenue");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 0, 51));
        jLabel51.setText("OUT Date & Time :");

        ex6.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 0, 51));
        jLabel53.setText("Floor No :");

        jLabel54.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 0, 51));
        jLabel54.setText("Rs:");

        ex7.setText(".....");

        javax.swing.GroupLayout VehiclexitLayout = new javax.swing.GroupLayout(Vehiclexit);
        Vehiclexit.setLayout(VehiclexitLayout);
        VehiclexitLayout.setHorizontalGroup(
            VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclexitLayout.createSequentialGroup()
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(57, 57, 57)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(VehiclexitLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                        .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(100, 100, 100)
                                .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel54)
                                        .addGap(56, 56, 56)
                                        .addComponent(ex7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addGap(18, 18, 18)
                                        .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addGap(75, 75, 75)
                                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 91, Short.MAX_VALUE))))))
        );
        VehiclexitLayout.setVerticalGroup(
            VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclexitLayout.createSequentialGroup()
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VehiclexitLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42)
                                    .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel41))
                            .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43)
                            .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(32, 32, 32))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(ex7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel54))
                                .addGap(29, 29, 29)))
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );

        getContentPane().add(Vehiclexit, "card8");

        jMenu1.setText("Employee");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Search Employee");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Parking");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Entry");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View Slots");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("jMenuItem5");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Settings");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("New Employee");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void vtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtMouseClicked

        DefaultTableModel dtm=(DefaultTableModel)vt.getModel();
        int ri=vt.getSelectedRow();
        if(ri!=-1){
            String u=(String)vt.getValueAt(ri,0);
            String s1=(String)vt.getValueAt(ri, 1);
            String s2=(String)vt.getValueAt(ri, 2);
           
       n1.setText(u);
            n2.setText(s1);
            n3.setText(s2);
            
                  
              delete.setEnabled(true);
              edit.setEnabled(true);
              n1.setEditable(false);
      n2.setEditable(true);
      n3.setEditable(true);
            
        }
    }//GEN-LAST:event_vtMouseClicked

    private void mKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mKeyReleased

        try{
             DefaultTableModel dtm=(DefaultTableModel)vt.getModel();
             int rc=dtm.getRowCount();
             while(rc--!=0){
                 dtm.removeRow(0);
             }
             String n=m.getText();
             db.likeQuery.setString(1, "%"+n+"%");
             ResultSet r=db.likeQuery.executeQuery();
             while(r.next()){
                 Vector row=new Vector();
                 row.add(r.getInt(1));
                  row.add(r.getString(2));
                   row.add(r.getInt(3));
                 dtm.addRow(row);
                 
             }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
  try{ 
        String x=n1.getText();
         db.deleteEmp.setString(1,x);
         db.deleteEmp.executeUpdate();
        
        JOptionPane.showMessageDialog(null," Member Deleted");
       

            
            
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); ;
        
    }                                        

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
java.awt.Container ct=getContentPane();
java.awt.CardLayout cd=(java.awt.CardLayout)ct.getLayout();
cd.show(ct, "2");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

String g1=t1.getText();
String g2=t2.getText();
String g3=t3.getText();
String g4=t4.getText();
try{
db.addUser.setString(1,g1);
db.addUser.setString(2,g2);


db.addUser.setString(3,g3);
db.addUser.setString(4,g4);

db.addUser.executeUpdate();
JOptionPane.showMessageDialog(this, "Resgistration sucessfull");




}
catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
}

    






        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       for(int i=0;i<vt.getModel().getRowCount(); i++){
           for(int j=1;j<=3;j++)
               vt.getModel().setValueAt(null,i,j-1);
           
        }

       try{
           DefaultTableModel dtm=(DefaultTableModel)vt.getModel();
           int rc=vt.getRowCount();
           while(rc--!=0){
               dtm.removeRow(0);
           }
           ResultSet rs=db.st.executeQuery("Select * from member_login");
           while(rs.next())
           {
               Vector row=new Vector();
                for(int j=1;j<=3;j++)
                {
                    row.add(rs.getObject(j));
                }
               dtm.addRow(row);
           }
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex.getMessage());
       }
    edit.setEnabled(false);
     delete.setEnabled(false);
     n1.setEditable(false);
     n2.setEditable(false);
     n3.setEditable(false);
     
    








        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  try{
             DefaultTableModel dtm=(DefaultTableModel)vt.getModel();
             int rc=dtm.getRowCount();
             while(rc--!=0){
                 dtm.removeRow(0);
             }
             
             if(mcb.equals("Name")){
             String n=m.getText();
             db.likeQuery.setString(1, "%"+n+"%");
             ResultSet r=db.likeQuery.executeQuery();
             while(r.next()){
                 Vector row=new Vector();
                 row.add(r.getInt(1));
                  row.add(r.getString(2));
                   row.add(r.getInt(3));
                 dtm.addRow(row);
                 edit.setEnabled(true);
             } 
             }
             else{
                  String n=m.getText();
             db.likeId.setString(1, "%"+n+"%");
             ResultSet r=db.likeId.executeQuery();
             while(r.next()){
                 Vector row=new Vector();
                 row.add(r.getInt(1));
                  row.add(r.getString(2));
                   row.add(r.getInt(3));
                 dtm.addRow(row);
                 edit.setEnabled(true);
             }
        }
  }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
            ex.printStackTrace();
        }
    
    edit.setEnabled(false);
     delete.setEnabled(false);
      n1.setEnabled(false);
       n2.setEnabled(false);
        n3.setEnabled(false);
    
  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    
    try{
        String g1=(String)n2.getText();
        String g2=n3.getText();
        int ph=Integer.parseInt(g2);
        String g3=n1.getText();
int uid=Integer.parseInt(g3);
        db.updateId.setString(1,g1);
        db.updateId.setInt(2,ph);
         db.updateId.setInt(3,uid);
       db.updateId.executeUpdate();
         
        
        
    }
catch(Exception ex){
     JOptionPane.showMessageDialog(null,ex.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void mcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcbActionPerformed

        
    }//GEN-LAST:event_mcbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String vt=(String)cm.getSelectedItem();
            
            ResultSet rs=db.st.executeQuery("select VacantSlots,FlooorNo from parking_area where VehicleType='"+vt+"' ");
            int x=0;
            String f="";
            while(rs.next())
            {
                x=rs.getInt(1);
                f=rs.getString(2);
                if(x>0)
                {
                    break;
                }
            }
            if(x!=0)
            {
                availStatus.setText("Available: "+x+" at Floor "+f);
                availStatus.setForeground(Color.green);
                pButton.setEnabled(true);
                
            }
            else
            {
                availStatus.setText("Not Available");
                availStatus.setForeground(Color.red);
                pButton.setEnabled(false);
                s11.setVisible(false);
                s22.setVisible(false);
                s33.setVisible(false);
                s44.setVisible(false);
                s55.setVisible(false);
                slipPrint.setEnabled(false);
                slipcancel.setEnabled(false);
              
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(AvpsAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
  String s1=ex1.getText();
  try{
       db.updateRev.setString(1,s1);
       db.updateRev.executeUpdate();
       JOptionPane.showMessageDialog(this, "Vehicle exit");
  }
catch(Exception ex1){
    System.out.print(ex1);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void slipPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slipPrintActionPerformed




 class MyPrint implements Printable
        {
            public int print(Graphics g, PageFormat pf, int page) throws PrinterException 
            {
                if (page > 0) { /* We have only one page, and 'page' is zero-based */
                    return NO_SUCH_PAGE;
                }
                /* User (0,0) is typically outside the imageable area, so we must
                 * translate by the X and Y values in the PageFormat to avoid clipping
                 */
                Graphics2D g2d = (Graphics2D)g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                /* Now print the window and its visible contents */
                s11.printAll(g);
                s22.printAll(g);
                s33.printAll(g);
                s44.printAll(g);
                s55.printAll(g);

                /* tell the caller that this page is part of the printed document */
                return PAGE_EXISTS;
            }
        }
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new MyPrint());
        boolean ok = job.printDialog();
        if (ok) 
        {
            try {
                 job.print();
            } catch (PrinterException ex) {
             /* The job did not successfully complete */
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_slipPrintActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed



 String vt=((String)cm.getSelectedItem());
        String vn=vehicleNo.getText().trim();
        if(!vn.equals(""))
        {
            int slipNo;
            try 
            {
                ResultSet rs1=db.st.executeQuery("select MAX(SlipNo) from Parking");
                if(rs1.next())
                    slipNo=rs1.getInt(1)+1;
                else
                    slipNo=0;
                //DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy h:mm a");
                //java.util.Date cd=new java.util.Date();
                //String InTime=dateFormat.format(cd);
                LocalDateTime InTime = LocalDateTime.now();
                ResultSet rs=db.st.executeQuery("select VacantSlots, FloorNo from Parking_Area where VehicleType='"+vt+"'");
                String f="";
                int vs=0;
                while(rs.next())
                {
                    vs=rs.getInt(1);
                    if(vs>0)
                    {
                        f=rs.getString(2);
                       db.st.executeUpdate("insert into Parking values("+slipNo+",'"+vt+"','"+vn+"',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'"+f+"',0,'Present')");
                     db.st.executeUpdate("update Parking_Area set VacantSlots="+(vs-1)+" WHERE floorNo = '"+f+"'");

                        s11.setText(slipNo+"");
                        s22.setText(vt);
                        s33.setText(vn);
                        s44.setText(InTime.format(DateTimeFormatter.ofPattern("dd-MMM-yyyy hh:mm a")));
                        s55.setText(f);
                       s11.setVisible(true);
                        s22.setVisible(true);
                         s33.setVisible(true);
                          s44.setVisible(true);
                           s55.setVisible(true);
                        slipPrint.setEnabled(true);
                        slipcancel.setEnabled(true);
                        vehicleNo.setText("");
                        break;
                    }
                }
                if(vs==0)
                    JOptionPane.showMessageDialog(null,"Parking Full!!");
                
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
                ex.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Plz Enter Vehicle No. !!!");
            s11.setVisible(false);
            s22.setVisible(false);
            s33.setVisible(false);
            s44.setVisible(false);
            s55.setVisible(false);
            slipPrint.setEnabled(false);
            slipcancel.setEnabled(false);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pButtonActionPerformed

    private void slipcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slipcancelActionPerformed




try {
            String sno=s11.getText().trim();
            String f=s55.getText().trim();
            if(!sno.equals(""))
            {
                int x=JOptionPane.showConfirmDialog(null, "Are you sure to Cancel Parking?");
                if(x==JOptionPane.YES_OPTION)
                {
                    ResultSet rs=db.st.executeQuery("select VacantSlots from Parking_Area where floorNo='"+f+"'");
                    rs.next();
                    int vs=rs.getInt(1);
                    db.st.executeUpdate("update Parking_Area set VacantSlots="+(vs+1)+" WHERE floorNo = '"+f+"'");
                    db.st.executeUpdate("Delete from Parking where SlipNo="+sno);
                    JOptionPane.showMessageDialog(null,"Record Removed( Parking Canceled)!!");
                    s11.setVisible(false);
                    s22.setVisible(false);
                    s33.setVisible(false);
                    s44.setVisible(false);
                    s55.setVisible(false);
                    slipPrint.setEnabled(false);
                    slipcancel.setEnabled(false);
                    vehicleNo.setText("");
                }
                
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_slipcancelActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed


 class MyPrint implements Printable
        {
            public int print(Graphics g, PageFormat pf, int page) throws PrinterException 
            {
                if (page > 0) { /* We have only one page, and 'page' is zero-based */
                    return NO_SUCH_PAGE;
                }
                /* User (0,0) is typically outside the imageable area, so we must
                 * translate by the X and Y values in the PageFormat to avoid clipping
                 */
                Graphics2D g2d = (Graphics2D)g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                /* Now print the window and its visible contents */
                ex1.printAll(g);
                 ex2.printAll(g);
                  ex3.printAll(g);
                   ex4.printAll(g);
                    ex5.printAll(g);
                     ex6.printAll(g);
                      ex7.printAll(g);

                /* tell the caller that this page is part of the printed document */
                return PAGE_EXISTS;
            }
        }
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new MyPrint());
        boolean ok = job.printDialog();
        if (ok) 
        {
            try {
                 job.print();
            } catch (PrinterException ex) {
             /* The job did not successfully complete */
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

  refresh();        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed

 slotUpdate.setVisible(true);
        v6.setEditable(true);
       v3.setEditable(true);
       v4.setEditable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_edit1ActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v1ActionPerformed

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v3ActionPerformed

    private void slotUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotUpdateActionPerformed


  try
        {
        String s1=v1.getText();
        String s2=v6.getText();
        int s3=Integer.parseInt(v3.getText());
        int s4=Integer.parseInt(v4.getText());
        db.st.executeUpdate("update Parking_Area set VehicleType='"+s2+"',TotalSlots="+s3+",VacantSlots="+s4+" where FloorNo='"+s1+"'");
        refresh();
        JOptionPane.showMessageDialog(null,"Updation Successfull !!");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }              // TODO add your handling code here:
    }//GEN-LAST:event_slotUpdateActionPerformed

    private void vt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vt1MouseClicked

 int row=vt1.getSelectedRow();
        Object s1=vt1.getModel().getValueAt(row, 0);
        Object s2=vt1.getModel().getValueAt(row, 1);
        Object s3=vt1.getModel().getValueAt(row, 2);
        Object s4=vt1.getModel().getValueAt(row, 3);
        v1.setText(s1.toString());
        v6.setText(s2.toString());
        v3.setText(s3.toString());
        v4.setText(s4.toString());
        edit1.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_vt1MouseClicked

    private void cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActionPerformed
   if(cbx.getSelectedItem().toString().equals("SlipNo"))
        s1.setText("Enter Slip No");
        else
        s1.setText("Enter Vehicle No");
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

java.awt.Container ct=getContentPane();
java.awt.CardLayout cd=(java.awt.CardLayout)ct.getLayout();
cd.show(ct, "card6");
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

java.awt.Container ct=getContentPane();
java.awt.CardLayout cd=(java.awt.CardLayout)ct.getLayout();
cd.show(ct, "card7");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

java.awt.Container ct=getContentPane();
java.awt.CardLayout cd=(java.awt.CardLayout)ct.getLayout();
cd.show(ct, "card8");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        
java.awt.Container ct=getContentPane();
java.awt.CardLayout cd=(java.awt.CardLayout)ct.getLayout();
cd.show(ct, "6");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed


java.awt.Container ct=getContentPane();
java.awt.CardLayout cd=(java.awt.CardLayout)ct.getLayout();
cd.show(ct, "2");    

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvpsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvpsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvpsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvpsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvpsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewEmp;
    private javax.swing.JPanel Searchemp;
    private javax.swing.JPanel Searchemp1;
    private javax.swing.JPanel VehicleEntry_;
    private javax.swing.JPanel Vehiclexit;
    private javax.swing.JPanel ViewSlots;
    private javax.swing.JLabel availStatus;
    private javax.swing.JComboBox<String> cbx;
    private javax.swing.JComboBox<String> cm;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JLabel ex1;
    private javax.swing.JLabel ex2;
    private javax.swing.JLabel ex3;
    private javax.swing.JLabel ex4;
    private javax.swing.JLabel ex5;
    private javax.swing.JLabel ex6;
    private javax.swing.JLabel ex7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField m;
    private javax.swing.JComboBox<String> mcb;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JButton pButton;
    private javax.swing.JPanel panal1;
    private javax.swing.JPanel panal2;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField s1;
    private javax.swing.JLabel s11;
    private javax.swing.JLabel s22;
    private javax.swing.JLabel s33;
    private javax.swing.JLabel s44;
    private javax.swing.JLabel s55;
    private javax.swing.JButton slipPrint;
    private javax.swing.JButton slipcancel;
    private javax.swing.JButton slotUpdate;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField v6;
    private javax.swing.JTextField vehicleNo;
    private javax.swing.JTable vt;
    private javax.swing.JTable vt1;
    // End of variables declaration//GEN-END:variables
}
