
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author om
 */
public class AvpsExit extends javax.swing.JFrame {

    /**
     * Creates new form AvpsExit
     */
    public AvpsExit() {
        initComponents();
    }

    AvpsExit(int sno, String name, String mid) {
      initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vehiclexit = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        cbx = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        ex1 = new javax.swing.JLabel();
        ex3 = new javax.swing.JLabel();
        ex2 = new javax.swing.JLabel();
        ex5 = new javax.swing.JLabel();
        ex4 = new javax.swing.JLabel();
        slipcancel = new javax.swing.JButton();
        cr = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        ex6 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        ex7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(102, 0, 102));

        jLabel37.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Vehicle Exit");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 255));

        jLabel38.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel38.setText("Avps parking bill");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(78, 78, 78))
        );

        jPanel9.setBackground(new java.awt.Color(51, 0, 51));

        jLabel39.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 204, 255));
        jLabel39.setText("Search By:");

        cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SLIP NO", "VEHICLE NO", " " }));
        cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 204, 255));
        jLabel40.setText("Slip No :");

        s1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 204, 255));
        jButton9.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButton9.setText("SEARCH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(40, 40, 40)
                        .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(27, 27, 27)
                        .addComponent(s1)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jLabel41.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 0, 51));
        jLabel41.setText("Vehicle Type : ");

        jLabel42.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 0, 51));
        jLabel42.setText("SlipNo : ");

        jLabel43.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 0, 51));
        jLabel43.setText("Vehicle No :");

        jLabel44.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 0, 51));
        jLabel44.setText("IN Date & Time :");

        jLabel45.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 0, 51));
        jLabel45.setText("Revenue:");

        ex1.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex3.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex2.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex5.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        ex4.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        slipcancel.setBackground(new java.awt.Color(51, 0, 51));
        slipcancel.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        slipcancel.setForeground(new java.awt.Color(255, 204, 255));
        slipcancel.setText("Print Bill");
        slipcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slipcancelActionPerformed(evt);
            }
        });

        cr.setBackground(new java.awt.Color(51, 0, 51));
        cr.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        cr.setForeground(new java.awt.Color(255, 204, 255));
        cr.setText("Collect Revenue");
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 0, 51));
        jLabel51.setText("OUT Date & Time :");

        ex6.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 0, 51));
        jLabel53.setText("Floor No :");

        jLabel54.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 0, 51));
        jLabel54.setText("Rs:");

        ex7.setText(".....");

        javax.swing.GroupLayout VehiclexitLayout = new javax.swing.GroupLayout(Vehiclexit);
        Vehiclexit.setLayout(VehiclexitLayout);
        VehiclexitLayout.setHorizontalGroup(
            VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclexitLayout.createSequentialGroup()
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VehiclexitLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel54)
                                        .addGap(56, 56, 56)
                                        .addComponent(ex7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addGap(64, 64, 64)
                                        .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(103, 103, 103)
                                        .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VehiclexitLayout.createSequentialGroup()
                                        .addComponent(jLabel53)
                                        .addGap(100, 100, 100)
                                        .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(VehiclexitLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(cr)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(slipcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(VehiclexitLayout.createSequentialGroup()
                                            .addComponent(jLabel51)
                                            .addGap(18, 18, 18)
                                            .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        VehiclexitLayout.setVerticalGroup(
            VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclexitLayout.createSequentialGroup()
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VehiclexitLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42)
                                    .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel41))
                            .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel43)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44)
                            .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(32, 32, 32))
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VehiclexitLayout.createSequentialGroup()
                                .addComponent(ex7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclexitLayout.createSequentialGroup()
                                .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel54))
                                .addGap(29, 29, 29)))
                        .addGap(15, 15, 15)
                        .addGroup(VehiclexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slipcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Vehiclexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Vehiclexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

String s3=(String)cbx.getSelectedItem();
String s2=s1.getText();
ResultSet rs;
try{
    if(s3.equalsIgnoreCase("Slip no")){
        db.exitSlip.setString(1,s2);
        rs=db.exitSlip.executeQuery();
        
    }
    else{
        db.exitVehNo.setString(1,s2);
        rs=db.exitVehNo.executeQuery();
        
    }
    if(rs.next()){
        int v1=rs.getInt(1);
        String v2=rs.getString(2);
          String v3=rs.getString(3);
          LocalDateTime v4=rs.getTimestamp(4).toLocalDateTime();
           LocalDateTime v5= LocalDateTime.now();
           String v6=rs.getString(6);
           long dh=Duration.between(v4,v5).toHours();
           long t;
           if(v2.equalsIgnoreCase("car")){
               t=20*(dh+1);
           }
           else{
             t=10*(dh+1);
           }
           ex1.setText(String.valueOf(v1));
           ex2.setText(v3);
           ex3.setText(v2);
           ex4.setText(v4.format(DateTimeFormatter.ofPattern("dd-mm-yyyy hh:mm a")));
            ex5.setText(v5.format(DateTimeFormatter.ofPattern("dd-mm-yyyy hh:mm a")));
             ex6.setText(v6);
              ex7.setText(t+"");
              db.updateOut.setInt(1,v1);
               db.updateOut.executeUpdate();
             
        
    }
    
}
catch(Exception ex1){
    System.out.println(ex1);
}







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void slipcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slipcancelActionPerformed

 class MyPrint implements Printable
        {
            public int print(Graphics g, PageFormat pf, int page) throws PrinterException 
            {
                if (page > 0) { /* We have only one page, and 'page' is zero-based */
                    return NO_SUCH_PAGE;
                }
                /* User (0,0) is typically outside the imageable area, so we must
                 * translate by the X and Y values in the PageFormat to avoid clipping
                 */
                Graphics2D g2d = (Graphics2D)g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                /* Now print the window and its visible contents */
                ex1.printAll(g);
                 ex2.printAll(g);
                  ex3.printAll(g);
                   ex4.printAll(g);
                    ex5.printAll(g);
                     ex6.printAll(g);
                      ex7.printAll(g);

                /* tell the caller that this page is part of the printed document */
                return PAGE_EXISTS;
            }
        }
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new MyPrint());
        boolean ok = job.printDialog();
        if (ok) 
        {
            try {
                 job.print();
            } catch (PrinterException ex) {
             /* The job did not successfully complete */
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_slipcancelActionPerformed

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
 String s1=ex1.getText();
  try{
      db.updateRev.setString(1,s1);
       db.updateRev.executeUpdate();
       JOptionPane.showMessageDialog(this, "Vehicle exit");
  }
catch(Exception ex1){
    System.out.print(ex1);
}        // TODO add your handling code here:
    }//GEN-LAST:event_crActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActionPerformed

   if(cbx.getSelectedItem().toString().equals("SlipNo"))
        s1.setText("Enter Slip No");
        else
        s1.setText("Enter Vehicle No");        // TODO add your handling code here:
    }//GEN-LAST:event_cbxActionPerformed

    /**
     * @param args the command line arguments
     */
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Vehiclexit;
    private javax.swing.JComboBox<String> cbx;
    private javax.swing.JButton cr;
    private javax.swing.JLabel ex1;
    private javax.swing.JLabel ex2;
    private javax.swing.JLabel ex3;
    private javax.swing.JLabel ex4;
    private javax.swing.JLabel ex5;
    private javax.swing.JLabel ex6;
    private javax.swing.JLabel ex7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField s1;
    private javax.swing.JButton slipcancel;
    // End of variables declaration//GEN-END:variables
}
